---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2
  # Temporary workaround to be able to test with the latest version of mixlib install locally.
  # Will be removed before merge.
  synced_folders:
    - ['/Users/serdar/chef/mixlib-install', '/home/vagrant/mixlib-install']

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private

suites:
  - name: default
    run_list:
      - recipe[test]
      - recipe[test::repo]
    attributes:

  - name: override_package_versions
    run_list:
      - recipe[test]
      - recipe[test::repo]
    attributes:
      test:
        chef-server-core:
          version: 12.0.4

  - name: override_package_versions_rc
    run_list:
      - recipe[test]
      - recipe[test::repo]
    attributes:
      apt-chef:
        repo-name: 'chef-current'
        uri: 'https://packagecloud.io/chef/current/ubuntu/'
      yum-chef:
        repositoryid: 'chef-current'
        baseurl: 'https://packagecloud.io/chef/current/el/6/$basearch'
      test:
        chef-server-core:
          version: 12.1.0-rc.3

  - name: local_package_install
    run_list:
      - recipe[test]
      - recipe[test::local]
    attributes:

  - name: chef
    run_list:
      - recipe[test::chef]

  - name: chefdk
    run_list:
      - recipe[test::chefdk]

  - name: upgrade
    run_list:
      - recipe[test::upgrade]

  - name: push_client
    # we don't yet have push client packages for trusty, only precise
    excludes: ['ubuntu-14.04']
    run_list:
      - recipe[test::push]

  - name: ingredient_config
    run_list:
      - recipe[test::ingredient_config]

  - name: different_channels
    run_list:
      - recipe[test::different_channels]
