environment:
  machine_user: vagrant
  machine_pass: vagrant
  CHEF_LICENSE: accept
  KITCHEN_YAML: kitchen.appveyor.yml

  matrix:
    - CHEF_VERSION: 16
    - CHEF_VERSION: 17

# don't build PRs twice
branches:
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

#faster cloning
clone_depth: 1

# Install the latest current build of Chef Workstation
install:
  - ps: iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chef-workstation -channel stable
  - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
  - ps: $PSVersionTable
  - ps: secedit /export /cfg $env:temp/export.cfg
  - ps: ((get-content $env:temp/export.cfg) -replace ('PasswordComplexity = 1', 'PasswordComplexity = 0')) | Out-File $env:temp/export.cfg
  - ps: ((get-content $env:temp/export.cfg) -replace ('MinimumPasswordLength = 8', 'MinimumPasswordLength = 0')) | Out-File $env:temp/export.cfg
  - ps: secedit /configure /db $env:windir/security/new.sdb /cfg $env:temp/export.cfg /areas SECURITYPOLICY
  - ps: net user /add $env:machine_user $env:machine_pass
  - ps: net localgroup administrators $env:machine_user /add

build_script:
  - ps: $env:PATH = "$env:PATH;c:\opscode\chef-workstation\bin\"; $env:CHEFWS_ENV_FIX = 1
  - ps: c:\opscode\chef-workstation\bin\chef.exe shell-init powershell | iex; cmd /c c:\opscode\chef-workstation\bin\chef.exe --version

test_script:
  - chef --version
  - chef.exe exec kitchen verify

deploy: off
