---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_infra
  deprecations_as_errors: true
  chef_license: accept-no-persist

platforms:
  - name: windows-2019

suites:
  - name: inspec
    run_list:
      - recipe[test::inspec]
