name             'chef-server-ingredient'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache 2.0'
description      'Manages Chef Server packages/add-ons, aka "ingredients"'
version          '0.3.0'
depends          'packagecloud'
