name 'chef-server-ingredient'
version '0.4.0'
maintainer 'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license 'Apache 2.0'
description 'Manages Chef Server packages/add-ons, aka "ingredients"'
source_url 'https://github.com/chef-cookbooks/chef-server-ingredient'
issues_url 'https://github.com/chef-cookbooks/chef-server-ingredient/issues'

depends 'packagecloud'
